dependencies:
  - name: postgresql
    version: 0.14.3
    repository: https://kubernetes-charts.storage.googleapis.com/
    condition: postgresql.enabled
  - name: redis
    version: 3.6.4
    repository: https://kubernetes-charts.storage.googleapis.com/
    condition: redis.enabled
