apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "fullname" . }}
  labels:
    app: {{ template "name" . }}
    chart: {{ template "chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  REDIS_HOST: "{{ .Release.Name }}-redis-master"
  REDIS_PORT: "6397"
  DB_HOST: "{{ .Release.Name }}-postgresql"
  DB_USER: "postgres"
  DB_NAME: "mastodon"
  DB_PORT: "5432"
  LOCAL_DOMAIN: "{{ .Values.domain }}"
  LOCAL_HTTPS: "{{ .Values.mastodon.locaHttps }}"
  SINGLE_USER_MODE: "{{ .Values.mastodon.singleUserMode }}"
  DEFAULT_LOCALE: "{{ .Values.mastodon.defaultLocale }}"
  SMTP_AUTH_METHOD: "{{ .Values.mastodon.smtpAuthMethod }}"
  SMTP_OPENSSL_VERIFY_MODE: "{{ .Values.mastodon.smtpOpensslVerifyMode }}"
  SMTP_PORT: "{{ .Values.mastodon.smtpPort }}"
  SMTP_SERVER: "{{ .Values.mastodon.smtpServer }}"
  SMTP_FROM_ADDRESS: "{{ .Values.mastodon.smtpFromAddress }}"
  SMTP_DELIVERY_METHOD: "sendmail"
