apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}
  labels:
    app: {{ template "name" . }}
    chart: {{ template "chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  selector:
    matchLabels:
      app: {{ template "name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "name" . }}
        release: {{ .Release.Name }}
    spec:
      {{- if .Values.image.pullSecrets }}
      imagePullSecrets:
      {{- range .Values.image.pullSecrets }}
        - name: {{ . }}
      {{- end }}
      {{- end }}
      tolerations:
      - key: "node.kubernetes.io/unreachable"
        operator: "Exists"
        effect: "NoExecute"
        tolerationSeconds: 1800
      - key: "node.kubernetes.io/not-ready"
        operator: "Exists"
        effect: "NoExecute"
        tolerationSeconds: 1800
      volumes:
      - name: mastodon-assets
        emptyDir: {}
      - name: mastodon-packs
        emptyDir: {}
      - name: mastodon-system
        emptyDir: {}
      containers:
      - name: {{ template "fullname" . }}-web
        image: "{{ .Values.image.registry }}/{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy | quote }}
        command: [
          "/bin/bash", "-c",
            "bundle exec rake assets:precompile && \
             bundle exec rake db:migrate --trace && \
             bundle exec rails s -p 3000 -b 0.0.0.0"
        ]
        ports:
        - name: web
          containerPort: 3000
        livenessProbe:
          httpGet:
            path: /about
            port: web
            httpHeaders:
            - name: X-Forwarded-Proto
              value: "https"
          initialDelaySeconds: 900
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: /about
            port: web
            httpHeaders:
            - name: X-Forwarded-Proto
              value: "https"
          initialDelaySeconds: 900
          periodSeconds: 3
        resources:
          requests:
            memory: {{ .Values.mastodon.web.resources.requests.memory }}
            cpu: {{ .Values.mastodon.web.resources.requests.cpu }}
        envFrom:
        - configMapRef:
            name: {{ template "fullname" . }}
        - secretRef:
            name: {{ template "fullname" . }}
        env:
        - name: DB_PASS
          valueFrom:
            secretKeyRef:
              name: "{{ .Release.Name }}-postgresql"
              key: postgres-password
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: "{{ .Release.Name }}-redis"
              key: redis-password
        volumeMounts:
          - mountPath: /mastodon/public/assets
            name: mastodon-assets
          - mountPath: /mastodon/public/packs
            name: mastodon-packs
          - mountPath: /mastodon/public/system
            name: mastodon-system
      - name: {{ template "fullname" . }}-sidekiq
        image: "{{ .Values.image.registry }}/{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy | quote }}
        command: [
          "bundle", "exec", "sidekiq",
            "-q", "default",
            "-q", "mailers",
            "-q", "pull",
            "-q", "push"
        ]
        resources:
          requests:
            memory: {{ .Values.mastodon.sidekiq.resources.requests.memory }}
            cpu: {{ .Values.mastodon.sidekiq.resources.requests.cpu }}
        envFrom:
        - configMapRef:
            name: {{ template "fullname" . }}
        - secretRef:
            name: {{ template "fullname" . }}
        volumeMounts:
          - mountPath: /mastodon/public/assets
            name: mastodon-assets
          - mountPath: /mastodon/public/packs
            name: mastodon-packs
          - mountPath: /mastodon/public/system
            name: mastodon-system
      - name: {{ template "fullname" . }}-streaming
        image: "{{ .Values.image.registry }}/{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy | quote }}
        command: [ "yarn", "start" ]
        ports:
        - name: streaming
          containerPort: 4000
        resources:
          requests:
            memory: {{ .Values.mastodon.streaming.resources.requests.memory }}
            cpu: {{ .Values.mastodon.streaming.resources.requests.cpu }}
        envFrom:
        - configMapRef:
            name: {{ template "fullname" . }}
        - secretRef:
            name: {{ template "fullname" . }}
