kind: PersistentVolume
apiVersion: v1
metadata:
  name: redis-volume
  namespace: mastodon
  labels:
    name: redis-volume
spec:
  capacity:
    storage: {{ .Values.redisStorage }}
  accessModes:
    - ReadWriteOnce
  gcePersistentDisk:
    pdName: "redis-volume"
    fsType: "ext4"

---

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: redis-volume-claim
  namespace: mastodon
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.redisStorage }}
