apiVersion: v1
kind: Secret
metadata:
  name: {{ template "fullname" . }}
  labels:
    app: {{ template "name" . }}
    chart: {{ template "chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  OTP_SECRET: {{ .Values.mastodon.secrets.otp | b64enc }}
  SECRET_KEY_BASE: {{ .Values.mastodon.secrets.keyBase | b64enc }}
  PAPERCLIP_SECRET: {{ .Values.mastodon.secrets.paperclip | b64enc }}
  tls.crt: {{ .Values.tlsCrt | b64enc }}
  tls.key: {{ .Values.tlsKey | b64enc }}
