apiVersion: v1
kind: Secret
metadata:
  name: mastodon-secrets
  namespace: mastodon
type: Opaque
data:
  OTP_SECRET: {{ .Values.otpSecret | b64enc }}
  SECRET_KEY_BASE: {{ .Values.secretKeyBase | b64enc }}
  PAPERCLIP_SECRET: {{ .Values.paperclipSecret | b64enc }}
  DB_PASS: {{ .Values.dbPass | b64enc }}

---

apiVersion: v1
kind: Secret
metadata:
  name: mastodon-tls
  namespace: mastodon
type: kubernetes.io/tls
data:
  tls.crt: {{ .Values.tlsCrt | b64enc }}
  tls.key: {{ .Values.tlsKey | b64enc }}
